# Project information
site_name: 歪朵拉开源硬件
site_description: Open Sourse Hardware
site_author: Mangogeek
site_url: http://widora.cn/


# Repository
repo_name: 'widora.cn'
repo_url: https://github.com/widora/widora.cn/
edit_uri: blob/master/docs/

# Copyright
copyright: 'Copyright &copy; 2017-2018 北京歪朵拉科技有限公司'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  feature:
    tabs: true
  palette:
    primary: Brown
    accent: Indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE30d"

# Customization
extra:
  search:
    language: 'en, zh'
extra:
  social:
    - type: github-alt
      link: https://github.com/widora/

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 主页: index.md
  - TinTin-A:
    - Index: authors-notes.md
    - Getting started: getting-started.md
    - License: license.md
  - TinTin-B:
    - Index: specimen.md
    - compliance: compliance.md


# Google Analytics
google_analytics:
  - "UA-109508401-9"
  - auto

